export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

// get order details
export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

// pay order
export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";
export const ORDER_MYORDERS_REQUEST = "ORDER_MYORDERS_REQUEST";
export const ORDER_MYORDERS_SUCCESS = "ORDER_MYORDERS_SUCCESS";
export const ORDER_MYORDERS_FAIL = "ORDER_MYORDERS_FAIL";
export const ORDER_MYORDERS_RESET = "ORDER_MYORDERS_RESET";

// get all orders
export const ORDER_ALL_REQUEST = "ORDER_ALL_REQUEST";
export const ORDER_ALL_SUCCESS = "ORDER_ALL_SUCCESS";
export const ORDER_ALL_FAIL = "ORDER_ALL_FAIL";
// update order to delivered
export const ORDER_DELIVER_REQUEST = "ORDER_DELIVER_REQUEST";
export const ORDER_DELIVER_SUCCESS = "ORDER_DELIVER_SUCCESS";
export const ORDER_DELIVER_FAIL = "ORDER_DELIVER_FAIL";
export const ORDER_DELIVER_RESET = "ORDER_DELIVER_RESET";

export const PAYPAL_CLIENT_ID = "AUtt9b3AscioBco-FThw6XP140JvkRtLF4eoikPHVuiq4KxMXqBlbGPb8FMehVOcJ7YFjhwUbgvnGTp4";