# Generated by Django 5.0.7 on 2024-07-19 23:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
