# Generated by Django 5.0.7 on 2024-07-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_remove_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="/placeholder.png", null=True, upload_to=""
            ),
        ),
    ]
