# Generated by Django 5.0.7 on 2024-08-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="itemsPrice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
